/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ınventorysystem;

import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Furkan
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        displayProduct();
        displayCustomer();
        GetDate();
    }
    
    Connection Con = null;
    Statement Stmt =null;
    ResultSet Rslt= null;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        close_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        orderQ_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        editProduct_btn = new javax.swing.JButton();
        addProduct_btn = new javax.swing.JButton();
        deleteProduct_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        product_Table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        home_lbl = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        customerName_lbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        date_lbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        orderID_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        price_lbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        revenue_lbl = new javax.swing.JLabel();
        print_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ENVANTER KONTROL SİSTEMİ");

        close_lbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\Furkan\\Desktop\\Inventory System Java\\close.png")); // NOI18N
        close_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_lblMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SİPARİŞ KAYIT EKRANI");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(407, 407, 407)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close_lbl))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(466, 466, 466)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(close_lbl)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Sipariş ID:");

        orderQ_txt.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Müşteri Adı:");

        editProduct_btn.setBackground(new java.awt.Color(51, 51, 255));
        editProduct_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        editProduct_btn.setForeground(new java.awt.Color(255, 255, 255));
        editProduct_btn.setText("Değiştir");
        editProduct_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProduct_btnMouseClicked(evt);
            }
        });

        addProduct_btn.setBackground(new java.awt.Color(51, 51, 255));
        addProduct_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addProduct_btn.setForeground(new java.awt.Color(255, 255, 255));
        addProduct_btn.setText("Ekle");
        addProduct_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProduct_btnMouseClicked(evt);
            }
        });

        deleteProduct_btn.setBackground(new java.awt.Color(51, 51, 255));
        deleteProduct_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        deleteProduct_btn.setForeground(new java.awt.Color(255, 255, 255));
        deleteProduct_btn.setText("Sil");
        deleteProduct_btn.setToolTipText("");
        deleteProduct_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteProduct_btnMouseClicked(evt);
            }
        });

        product_Table.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        product_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün ID", "Ürün Adı", "Adet", "Fiyat", "Kategori"
            }
        ));
        product_Table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        product_Table.setRowHeight(25);
        product_Table.setSelectionBackground(new java.awt.Color(51, 51, 255));
        product_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(product_Table);

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        home_lbl.setBackground(new java.awt.Color(51, 51, 255));
        home_lbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        home_lbl.setForeground(new java.awt.Color(255, 255, 255));
        home_lbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\Furkan\\Desktop\\Inventory System Java\\homeicon.png")); // NOI18N
        home_lbl.setBorder(null);
        home_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_lblMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Ürün Tablosu");

        orderTable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sipariş ID", "Ürün Adı", "Sipariş Adedi", "Birim Fiyat", "Total"
            }
        ));
        orderTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        orderTable.setRowHeight(25);
        orderTable.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jScrollPane2.setViewportView(orderTable);

        customerTable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Müşteri ID", "Müşteri Adı", "Telefon", "Adres", "E-Posta"
            }
        ));
        customerTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        customerTable.setRowHeight(25);
        customerTable.setSelectionBackground(new java.awt.Color(51, 51, 255));
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(customerTable);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Tarih:");

        customerName_lbl.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        customerName_lbl.setForeground(new java.awt.Color(51, 51, 255));
        customerName_lbl.setText("müşteri");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Müşteri Tablosu");

        date_lbl.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        date_lbl.setForeground(new java.awt.Color(51, 51, 255));
        date_lbl.setText("00.00.0000");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Sipariş Adedi:");

        orderID_txt.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Birim Fiyat:");

        price_lbl.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        price_lbl.setForeground(new java.awt.Color(51, 51, 255));
        price_lbl.setText("----- ");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Toplam Kazanç:");

        revenue_lbl.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        revenue_lbl.setForeground(new java.awt.Color(51, 51, 255));
        revenue_lbl.setText("------");

        print_btn.setBackground(new java.awt.Color(51, 51, 255));
        print_btn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        print_btn.setForeground(new java.awt.Color(255, 255, 255));
        print_btn.setText("Yazdır");
        print_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(home_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(addProduct_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(editProduct_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(deleteProduct_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7))
                                        .addGap(69, 69, 69)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(orderQ_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(customerName_lbl)
                                            .addComponent(date_lbl)
                                            .addComponent(orderID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(price_lbl))))
                                .addGap(8, 8, 8)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(264, 264, 264))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(36, 36, 36)
                .addComponent(revenue_lbl)
                .addGap(59, 59, 59)
                .addComponent(print_btn)
                .addGap(103, 103, 103))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(price_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(orderID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(orderQ_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerName_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addProduct_btn)
                                .addComponent(editProduct_btn)
                                .addComponent(deleteProduct_btn))
                            .addComponent(home_lbl))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(revenue_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(print_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void displayProduct(){
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorydb?useTimezone=trueServerTimezone=UTC","root","");
            Stmt = Con.createStatement();
            Rslt = Stmt.executeQuery("select * from producttable");
            product_Table.setModel(DbUtils.resultSetToTableModel(Rslt));
 
        }catch(SQLException e)
        {
            e.printStackTrace();
        }
    }
    
    public void displayCustomer(){
           try{
               Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorydb?useTimezone=trueServerTimezone=UTC","root","");
               Stmt = Con.createStatement();
               Rslt = Stmt.executeQuery("select * from customertable");
               customerTable.setModel(DbUtils.resultSetToTableModel(Rslt));

           }catch(SQLException e)
           {
               e.printStackTrace();
           }
       }
    
    public void updateInventory(){
        int currentStock = prevStock - Integer.valueOf(orderQ_txt.getText());
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorydb?useTimezone=trueServerTimezone=UTC","root","");
            String UpdateQuery = "update producttable set Quantity='"+currentStock+"where ProductID ="+productID;
            Statement Add=Con.createStatement();
            Add.executeUpdate(UpdateQuery);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void GetDate(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        date_lbl.setText(dtf.format(now));
    }
    
    private void close_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_lblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_lblMouseClicked

    private void editProduct_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProduct_btnMouseClicked
        if(orderQ_txt.getText().isEmpty()||product_txt.getText().isEmpty()||productQ_txt.getText().isEmpty()||productP_txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Bazı bilgiler eksik,güncellenemiyor");
        }
        else{
            try{
                Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorydb?useTimezone=trueServerTimezone=UTC","root","");
                String UpdateQuery = "update producttable set ProductName='"+product_txt.getText()+"'"+",Quantity='"+productQ_txt.getText()+"'"
                +",Price='"+productP_txt.getText()+"'"+",Category='"+CatCombo.getSelectedItem().toString()+"'"+"where ProductID ="+orderQ_txt.getText();
                Statement Add = Con.createStatement();
                Add.executeUpdate(UpdateQuery);
                JOptionPane.showMessageDialog(this, "Ürün başarıyla güncellendi!");
                displayProduct();
            }catch(Exception e){
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_editProduct_btnMouseClicked
int Price,i=1,total,Revenue;
String ProductName,price,customerName;
    private void addProduct_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProduct_btnMouseClicked
        if(controller == 0 || orderQ_txt.getText().isEmpty() || price.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Sipariş miktarı giriniz ve tablo seçimlerini yapınız!!");
        }
        else
        {
            try{
                Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorydb?useTimezone=trueServerTimezone=UTC","root","");
                PreparedStatement add= Con.prepareStatement("insert into ordertable values(?,?,?,?,?)");
                add.setInt(1,Integer.valueOf(orderID_txt.getText()));
                add.setString(2,customerName);
                add.setInt(3,Integer.valueOf(orderQ_txt.getText()));
                add.setInt(4,Price);
                add.setInt(5,total);
                int row=add.executeUpdate();
                JOptionPane.showMessageDialog(this,"Ürün Başarıyla Eklendi!!");
                Con.close();
                
            }catch(SQLException e){
                e.printStackTrace();
            }
            Price=Integer.valueOf(price);
            total=Price*Integer.valueOf(orderQ_txt.getText());
            Vector v = new Vector();
            v.add(i);
            v.add(ProductName);
            v.add(orderQ_txt.getText());
            v.add(Price);
            v.add(total);
            DefaultTableModel dt = (DefaultTableModel)orderTable.getModel();
            dt.addRow(v);           
            Revenue=Revenue+total;
            revenue_lbl.setText(Revenue+"TL");
            updateInventory();
            i++;
        }
    }//GEN-LAST:event_addProduct_btnMouseClicked

    private void deleteProduct_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteProduct_btnMouseClicked
        if(orderQ_txt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Silmek için önce ürün eklemelisin :D");
        }
        else{
            try{
                Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorydb?useTimezone=trueServerTimezone=UTC","root","");
                String Id=orderQ_txt.getText();
                String Query="Delete from producttable where ProductID="+Id;
                Statement Add = Con.createStatement();
                Add.executeUpdate(Query);
                displayProduct();
                JOptionPane.showMessageDialog(this,"Ürün başarıyla silindi!");
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_deleteProduct_btnMouseClicked
int controller=0,productID,prevStock;
    private void product_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_TableMouseClicked
        DefaultTableModel model = (DefaultTableModel)product_Table.getModel();
        int Myindex = product_Table.getSelectedRow();
        productID = Integer.valueOf(model.getValueAt(Myindex,0).toString());
        ProductName=model.getValueAt((Myindex), 1).toString();
        prevStock = Integer.valueOf(model.getValueAt(Myindex, 2).toString());
        price=model.getValueAt((Myindex), 3).toString();
        price_lbl.setText(price.toString());
        controller=1;

    }//GEN-LAST:event_product_TableMouseClicked

    private void home_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_lblMouseClicked
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_home_lblMouseClicked

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)customerTable.getModel();
        int Myindex = customerTable.getSelectedRow();
        customerName_lbl.setText(model.getValueAt((Myindex), 1).toString());
        customerName = (model.getValueAt((Myindex), 1).toString()); 
                
    }//GEN-LAST:event_customerTableMouseClicked

    private void print_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_btnMouseClicked
        try{
            orderTable.print();
        }catch(Exception exp){
            exp.printStackTrace();
        }
    }//GEN-LAST:event_print_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct_btn;
    private javax.swing.JLabel close_lbl;
    private javax.swing.JLabel customerName_lbl;
    private javax.swing.JTable customerTable;
    private javax.swing.JLabel date_lbl;
    private javax.swing.JButton deleteProduct_btn;
    private javax.swing.JButton editProduct_btn;
    private javax.swing.JButton home_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField orderID_txt;
    private javax.swing.JTextField orderQ_txt;
    private javax.swing.JTable orderTable;
    private javax.swing.JLabel price_lbl;
    private javax.swing.JButton print_btn;
    private javax.swing.JTable product_Table;
    private javax.swing.JLabel revenue_lbl;
    // End of variables declaration//GEN-END:variables

    private Object parseString(int Price) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
